// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Testro.TestingManagement.WebApi.DataAccess;

namespace Testro.TestingManagement.WebApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.Requirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<int?>("TestProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestProjectId");

                    b.ToTable("Requirements");
                });

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("Result")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("TestScenarioId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TestScenarioId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.TestProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TestProjects");
                });

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.TestScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("TestProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestProjectId");

                    b.ToTable("TestScenarios");
                });

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.Requirement", b =>
                {
                    b.HasOne("Testro.TestingManagement.WebApi.Models.TestProject", null)
                        .WithMany("Requirements")
                        .HasForeignKey("TestProjectId");
                });

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.TestCase", b =>
                {
                    b.HasOne("Testro.TestingManagement.WebApi.Models.TestScenario", null)
                        .WithMany("TestCases")
                        .HasForeignKey("TestScenarioId");
                });

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.TestScenario", b =>
                {
                    b.HasOne("Testro.TestingManagement.WebApi.Models.TestProject", null)
                        .WithMany("TestScenarios")
                        .HasForeignKey("TestProjectId");
                });

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.TestProject", b =>
                {
                    b.Navigation("Requirements");

                    b.Navigation("TestScenarios");
                });

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.TestScenario", b =>
                {
                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
