// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Testro.TestingManagement.WebApi.DataAccess;

namespace Testro.TestingManagement.WebApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("TestScenarioId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TestScenarioId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.TestProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Requirements")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TestProjects");
                });

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.TestScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("TestProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestProjectId");

                    b.ToTable("TestScenarios");
                });

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.TestCase", b =>
                {
                    b.HasOne("Testro.TestingManagement.WebApi.Models.TestScenario", "TestScenario")
                        .WithMany("TestCases")
                        .HasForeignKey("TestScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestScenario");
                });

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.TestScenario", b =>
                {
                    b.HasOne("Testro.TestingManagement.WebApi.Models.TestProject", "TestProject")
                        .WithMany("TestScenarios")
                        .HasForeignKey("TestProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestProject");
                });

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.TestProject", b =>
                {
                    b.Navigation("TestScenarios");
                });

            modelBuilder.Entity("Testro.TestingManagement.WebApi.Models.TestScenario", b =>
                {
                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
